/*
 * WheelStructs.h
 *
 *  Created on: 19 ����. 2018 �.
 *      Author: Alex
 */

#ifndef _APS_COMMANDSTRUCTS_H_
#define _APS_COMMANDSTRUCTS_H_

#include "ConstantsCommon.h"
#include "ADCController.h"
#include "os_portmacro.h"

typedef enum
{
    UNKNOWN_COMMAND = 0b11111111,

    WHEEL_COMMAND_TYPE = 0b10000000,
    CMD_WHEEL_UP   = WHEEL_COMMAND_TYPE | 0b0001,
    CMD_WHEEL_DOWN = WHEEL_COMMAND_TYPE | 0b0010,
    CMD_WHEEL_STOP = WHEEL_COMMAND_TYPE | 0b0100,
    CMD_WHEEL_AUTO = WHEEL_COMMAND_TYPE | 0b1000,

    MEMORY_COMMAND_TYPE = 0b01000000,
    CMD_MEM_CLEAR       = MEMORY_COMMAND_TYPE | 0b0001,
    CMD_LEVELS_SAVE     = MEMORY_COMMAND_TYPE | 0b0010,
    CMD_LEVELS_SAVE_MAX = MEMORY_COMMAND_TYPE | 0b0011,
    CMD_LEVELS_SAVE_MIN = MEMORY_COMMAND_TYPE | 0b0100,
    CMD_LEVELS_GET      = MEMORY_COMMAND_TYPE | 0b0101,
    CMD_LEVELS_GET_MAX  = MEMORY_COMMAND_TYPE | 0b0110,
    CMD_LEVELS_GET_MIN  = MEMORY_COMMAND_TYPE | 0b0111,
    CMD_LEVELS_SHOW     = MEMORY_COMMAND_TYPE | 0b1000,
    CMD_GET_COMPRESSOR_PRESSURE = MEMORY_COMMAND_TYPE | 0b1001,
    CMD_SET_COMPRESSOR_MAX_PRESSURE = MEMORY_COMMAND_TYPE | 0b1010,
    CMD_SET_COMPRESSOR_MIN_PRESSURE = MEMORY_COMMAND_TYPE | 0b1011,
    CMD_GET_COMPRESSOR_MAX_PRESSURE = MEMORY_COMMAND_TYPE | 0b1100,
    CMD_GET_COMPRESSOR_MIN_PRESSURE = MEMORY_COMMAND_TYPE | 0b1101,

    SETTINGS_COMMAND_TYPE = 0b00100000,
    //CMD_XXX = SETTINGS_COMMAND_TYPE | 0b0001,
    //CMD_XXX = SETTINGS_COMMAND_TYPE | 0b0010,

    ENV_COMMAND_TYPE = 0b00010000,
    CMD_GET_VERSION  = ENV_COMMAND_TYPE | 0b0001,
    CMD_GET_BATTERY = ENV_COMMAND_TYPE | 0b0010,
    CMD_HELP = ENV_COMMAND_TYPE | 0b1000,
} COMMAND_TYPE;

typedef struct
{
    COMMAND_TYPE commandType;                  // command type, such as wheel command (up, down, stop), memory command (save, get, etc).
    portSHORT argv[COMMAND_ARGS_LIMIT];
    portCHAR argc;
} Command;


#endif /* _APS_COMMANDSTRUCTS_H_ */
