#ifndef SOURCE_HETPINS_INCLUDES_HETCONSTANTS_H_
#define SOURCE_HETPINS_INCLUDES_HETCONSTANTS_H_

// approved
#define FORWARD_LEFT_UP_PIN 31
#define FORWARD_LEFT_DOWN_PIN 15
#define FORWARD_RIGHT_UP_PIN 25
#define FORWARD_RIGHT_DOWN_PIN 7

#define BACK_LEFT_UP_PIN 2
#define BACK_LEFT_DOWN_PIN 3
#define BACK_RIGHT_UP_PIN 22
#define BACK_RIGHT_DOWN_PIN 27

#define COMPRESSOR_HET_PIN 26

#define LED_1_HET_PIN 18

#endif /* SOURCE_HETPINS_INCLUDES_HETCONSTANTS_H_ */
