#ifndef SOURCE_HETPINS_INCLUDES_HETCONSTANTS_H_
#define SOURCE_HETPINS_INCLUDES_HETCONSTANTS_H_

#define FORWARD_LEFT_UP_PIN 20
#define FORWARD_LEFT_DOWN_PIN 18
#define FORWARD_RIGHT_UP_PIN 16
#define FORWARD_RIGHT_DOWN_PIN 30

#define BACK_LEFT_UP_PIN 14
#define BACK_LEFT_DOWN_PIN 12
#define BACK_RIGHT_UP_PIN 22
#define BACK_RIGHT_DOWN_PIN 25

#endif /* SOURCE_HETPINS_INCLUDES_HETCONSTANTS_H_ */
